# Generated by Django 4.2.24 on 2025-09-13 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('objectives', models.TextField(blank=True, null=True, verbose_name='Objetivos')),
                ('constraints', models.TextField(blank=True, null=True, verbose_name='Restrições')),
                ('language', models.CharField(default='pt-BR', max_length=10, verbose_name='Idioma')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Desafio',
                'verbose_name_plural': 'Desafios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('summary', models.TextField(verbose_name='Resumo')),
                ('categories', models.JSONField(default=list, verbose_name='Categorias')),
                ('difficulty', models.CharField(choices=[('FACIL', 'Fácil'), ('MEDIO', 'Médio'), ('DIFICIL', 'Difícil')], max_length=10, verbose_name='Dificuldade')),
                ('approaches', models.JSONField(default=list, verbose_name='Abordagens')),
                ('recommended_approach', models.CharField(max_length=200, verbose_name='Abordagem Recomendada')),
                ('complexity_time', models.CharField(max_length=50, verbose_name='Complexidade de Tempo')),
                ('complexity_space', models.CharField(max_length=50, verbose_name='Complexidade de Espaço')),
                ('assumptions', models.TextField(blank=True, null=True, verbose_name='Suposições')),
                ('references', models.TextField(blank=True, null=True, verbose_name='Referências')),
                ('model', models.CharField(default='gpt-4o-mini', max_length=100, verbose_name='Modelo')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Dados Brutos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='desafios.challenge', verbose_name='Desafio')),
            ],
            options={
                'verbose_name': 'Análise',
                'verbose_name_plural': 'Análises',
                'ordering': ['-created_at'],
            },
        ),
    ]
