# Generated by Django 4.2.24 on 2025-09-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='recommended_solution',
            field=models.TextField(default='Solução não disponível', verbose_name='Solução Recomendada'),
        ),
    ]
